# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Columbus Regional Rail Plan
tagline: It's time for Columbus to catch up with its peer cities.
description: >- # this means to ignore newlines until "baseurl:"
  A fantasy transit map of places and ways where Columbus can build mass transit.
baseurl: '/columbus-regional-rail/'
permalink: /:title/
image: static/icon.png

author:
  name: Ben Keith
  twitter: benlkeith
  mastodon: https://urbanists.social/@benlk
  url: https://benlk.com/


collections:
  lines:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "lines"
    values:
      layout: "line"
  - scope:
      path: "_data/geojson/*.json"
    values:
      type: "geojson"
      geojson: true
      layout: "geojson"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _sass
  sourcemap: always

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - serve.sh
  - .sass-cache/
  - .jekyll-cache/
  - .github/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _data/
